### ISSUE TITLE
Add links to video and slides on talks pages

### ISSUE THREAD

**Issue by merwok** [pyconca/2012-web#71]
It would be great if each page could link to the pyvideo page and the slides, when the speaker put them online.  Macros could probably be used to reduce the boilerplate.

**Comment by codersquid** [comment]
I might be able to write a script to get all of required links. maybe only
with access to Carl's db (which I  can get). I might need an api key for
pyvideo in order to grab related links, so I'll ask Will about it.

To clarify, pyvideo has related urls listed on each talk's page, thus those
could be obtained programmatically. but likely would not be complete.

wrt to Carl's db, it has records that have the pyconca keys, along with the
pyvideo, youtube and archives urls. I don't know if it has related links.

following on all of this, I don't know if you want to provide a pyconca api
for creating talk metadata and subsequently creating templates for it. it
might be better to add them by hand for now and work out what is the best
thing to enhance next (crafting the api and related models and templates,
or some other features).

**Comment by merwok** [comment]
If the pyvideo pages already link to the slides and all, then the pycon.ca talk pages need only one link to pyvideo.  There are 51 videos, and URIs like http://pyvideo.org/video/id (i.e. without the slug) do work, so it could be simpler to manually add a macro like {{pyvideo 42}}.  If that sounds good, I could get to it this week.

**Comment by codersquid** [comment]
The macro id is cool.

Do you want me to get the associated ids to you so that you don't have to do them by hand? Probably just a sql query on Carl's db.

**Comment by wolever** [comment]
I could drop this in today if you can get me a list mapping PyVideo IDs to PyConCA IDs.

**Comment by codersquid** [comment]
emailed to you
